version: "3.9"
   
services:
  web:
    environment:
      ELASTIC_APM_SERVER_URL: "http://apm-server:8200"
      ELASTIC_APM_ENABLED: "true"
      ELASTIC_APM_SECRET_TOKEN: ""
      ELASTIC_APM_DEBUG: "true"
    networks: 
        - elk_elastic
  db:
    networks: 
        - elk_elastic

networks: 
    elk_elastic:
        external: true